site_name: Falon Darville's Blog
theme:
  name: material
  features:
    - navigation.sections
  logo: assets/images/bug-3.png
  favicon: assets/images/bug-3.png
  font: 
      text: Playfair Display
plugins:
  - blog:
      blog_dir: .
      post_url_format: "{slug}"
  - search
  - tags

nav:
  - index.md

extra_css:
  - stylesheets/extra.css
