site_name: Falon Darville
theme:
  name: material
  features:
    - navigation.sections
plugins:
  - blog:
      blog_dir: .
  - search
  - tags
nav:
  - index.md
plugins:
  - blog:
      post_url_format: "{slug}"

